library(renv)
renv::init(project = "~/Documents/multires_bhicect/HiC_enrichment/HiC_zscore_explore/")

renv::install("tidyverse")
renv::install("furrr")
renv::install("Matrix")
renv::install("viridis")
renv::install("seriation")
renv::install("caret")
renv::install("bioc::GenomicRanges")
renv::install("bioc::liftOver")
renv::install("bioc::AnnotationHub")
renv::install("ggridges")
renv::install("svglite")
renv::install("data.tree")

renv::snapshot()
